# Generated by Django 3.2.9 on 2021-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name')),
                ('password', models.CharField(max_length=50, verbose_name='User Password')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
    ]
