# Generated by Django 3.2.9 on 2021-12-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='User Name')),
                ('Password', models.CharField(max_length=50, verbose_name='User Password')),
                ('Email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
    ]
