# Generated by Django 3.2.9 on 2021-12-04 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query_Image', models.ImageField(upload_to='images/')),
                ('Title', models.CharField(max_length=30, verbose_name='Query title')),
                ('Description', models.TimeField(max_length=300, verbose_name='Query Description')),
                ('Posted_Date', models.DateField(default=datetime.date.today, verbose_name='Query Posted Date')),
                ('Good_Name', models.CharField(max_length=30, verbose_name='Query Owner Name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.demo')),
            ],
        ),
    ]
