# Generated by Django 3.2.9 on 2021-12-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Description',
            field=models.CharField(max_length=300, verbose_name='Query Description'),
        ),
        migrations.AlterField(
            model_name='query',
            name='Query_Image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
