# Generated by Django 3.2.9 on 2021-12-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_query_query_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Query_Image',
            field=models.ImageField(upload_to='media/%y'),
        ),
    ]
