# Generated by Django 3.2.9 on 2021-12-05 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_query_query_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('date_comment', models.DateField(default=datetime.date.today, verbose_name='message posted data')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.query')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.demo')),
            ],
        ),
    ]
