# Generated by Django 3.2.9 on 2021-12-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='Query title'),
        ),
    ]
