# Generated by Django 3.2.9 on 2021-12-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_query_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Posted_Date',
        ),
    ]
