# Generated by Django 3.2.9 on 2021-12-08 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_query_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Posted_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
