# Generated by Django 3.2.9 on 2021-12-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='completename',
            field=models.CharField(default=0, max_length=100, verbose_name='complete name'),
            preserve_default=False,
        ),
    ]
