# Generated by Django 3.2.9 on 2021-12-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_demo_completename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='query',
            name='Good_Name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='Query_Image',
        ),
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
