# Generated by Django 3.2.9 on 2021-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20211211_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='User_Image',
            field=models.ImageField(null=True, upload_to='media/%y'),
        ),
    ]
