# Generated by Django 3.2.9 on 2021-12-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_demo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='User_Image',
            field=models.ImageField(default=0, upload_to='media/%y'),
            preserve_default=False,
        ),
    ]
