# Generated by Django 3.2.9 on 2021-12-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_demo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='User_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%y'),
        ),
    ]
