# Generated by Django 3.2.9 on 2021-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20211211_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
