# Generated by Django 3.2.9 on 2021-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20211212_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query_type',
            new_name='query_type1',
        ),
        migrations.AddField(
            model_name='query',
            name='query_type2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_type3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_type4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_type5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_type6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
