# Generated by Django 3.2.9 on 2021-12-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20211213_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query_type1',
            new_name='query_type',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query_type2',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query_type3',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query_type4',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query_type5',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query_type6',
        ),
    ]
