# Generated by Django 3.2.9 on 2021-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='follwers_count',
            field=models.IntegerField(default=0),
        ),
    ]
