# Generated by Django 3.2.9 on 2021-12-31 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_demo_follwers_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaisedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Query title')),
                ('Posted_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('query_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.demo')),
            ],
        ),
    ]
