# Generated by Django 3.2.9 on 2022-01-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_raisedquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField(default=0)),
                ('whos_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.demo')),
            ],
        ),
    ]
