# Generated by Django 3.2.9 on 2022-01-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_alter_followers_whos_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='follwers_count',
        ),
    ]
