# Generated by Django 3.2.9 on 2022-01-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_remove_demo_follwers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='whos_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.demo'),
        ),
    ]
