# Generated by Django 3.2.9 on 2022-01-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_alter_followers_whos_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_type',
        ),
        migrations.CreateModel(
            name='QueryTagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.query')),
            ],
        ),
    ]
