# Generated by Django 3.2.9 on 2022-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_auto_20220122_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='check_follow',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
