# Generated by Django 3.2.9 on 2022-01-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_followers_check_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.query')),
            ],
        ),
    ]
