# Generated by Django 3.2.9 on 2022-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_auto_20220124_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='AboutMe',
            field=models.CharField(max_length=3000, verbose_name='aboutme'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='City',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_City',
            field=models.CharField(max_length=50, verbose_name='educationcity'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Country',
            field=models.CharField(max_length=50, verbose_name='educationcountry'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_From',
            field=models.DateTimeField(verbose_name='Current_Education_Date_From'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_To',
            field=models.DateTimeField(verbose_name='Current_Education_Date_To'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Place',
            field=models.CharField(max_length=1000, verbose_name='current education place'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='DateOfBirth',
            field=models.DateTimeField(verbose_name='dateofbirth'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Education_type',
            field=models.CharField(max_length=100, verbose_name='education_type'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Gender',
            field=models.CharField(max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Interest',
            field=models.CharField(max_length=3000, verbose_name='interest'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='User_Type',
            field=models.CharField(max_length=50, verbose_name='usertype'),
        ),
    ]
