# Generated by Django 3.2.9 on 2022-01-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_auto_20220124_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_From',
            field=models.DateField(verbose_name='Current_Education_Date_From'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_To',
            field=models.DateField(verbose_name='Current_Education_Date_To'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='DateOfBirth',
            field=models.DateField(verbose_name='dateofbirth'),
        ),
    ]
