# Generated by Django 3.2.9 on 2022-01-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_auto_20220124_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_From',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_To',
            field=models.DateField(),
        ),
    ]
