# Generated by Django 3.2.9 on 2022-01-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_auto_20220124_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Current_Education_Date_To',
            field=models.DateField(blank=True, null=True),
        ),
    ]
