# Generated by Django 3.2.9 on 2022-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_auto_20220124_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='dateofbirth'),
        ),
    ]
