# Generated by Django 3.2.9 on 2022-01-24 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0050_auto_20220124_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
