# Generated by Django 3.2.9 on 2022-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0052_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
